import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function topBar ({ children }) {
  return (
    <html>
      <body>
        <div className="topBar">
          <Link href="/" div className="frontend">Frontend Developer</Link>
          <div className="folder">
            <div className="aboutMe">About Me</div>
            <Link href="/education" className="education">Education</Link>
            <Link href="skills" className="skills">Skills</Link>
            <div className="project">Project</div>
            <div className="contact">Contact</div>
          </div>
        </div>
        {children}
      </body>
    </html>
  )
}